version: "3.9"

services:
  db:
    build: mongoDb/
    image: db:1.0.0
  backend:
    build: .
    image: backend:1.0.0
    depends_on:
      - db
    # ports:
    #   - "5000:1234"
  nginx:
    build: nginx
    image: mynginx:latest
    depends_on:
      - backend
    ports:
      - "6000:4000"
